---
- name: prepare to install ELK. Docker installation # Установка докера на web_servers / elastic_server / kibana_server
  hosts: 
    - elastic_server
    - kibana_server
    - web_servers
  become: yes

  roles: 
    - role: docker_installation

- name: elasticsearch installation # Установка elasticsearch на elastic_server
  hosts: elastic_server
  become: yes

  vars_files: ./elasticsearch/vars.yml

  tasks:
    - name: pull elasticsearch image # Скачивание elasticsearch docker image
      docker_image:
        name: "elasticsearch:{{ elk_version }}"
        source: pull

    - name: run elasticsearch # Запуск elasticsearch и настройка контейнера
      docker_container:
        name: elasticsearch_node
        image: "elasticsearch:{{ elk_version }}"
        state: started
        published_ports:
          - 9200:9200
          - 9300:9300
        env:
          discovery.type: single-node
          network.host: 0.0.0.0
          xpack.security.enabled: false

- name: kibana installation # Установка kibana на kibana_server
  hosts: kibana_server
  become: yes

  vars_files: ./elasticsearch/vars.yml

  tasks:
    - name: pull kibana image # Скачивание kibana docker image
      docker_image:
        name: "kibana:{{ elk_version }}"
        source: pull

    - name: wait for elasticsearch to start # Ожидание запуска elastic_server
      wait_for:
        host: "{{ groups['elastic_server'][0] }}"
        port: 9200

    - name: run kibana # Запуск kibana и настройка контейнера
      docker_container:
        name: kibana_node
        image: "kibana:{{ elk_version }}"
        state: started
        published_ports:
          - 5601:5601
        env: 
          ELASTICSEARCH_HOSTS: "http://{{ groups['elastic_server'][0] }}:9200"

- name: filebeat installation # Установка filebeat на web_servers
  hosts: web_servers
  become: yes

  vars_files: ./elasticsearch/vars.yml

  tasks:
    - name: copy filebeat.yml # Копирование файла настроек filebeat
      template:
        src: ./elasticsearch/filebeat.docker.yml.j2
        dest: /media/filebeat.docker.yml
      notify: restart filebeat

    - name: pull filebeat image # Скачивание filebeat docker image
      docker_image:
        name: "elastic/filebeat:{{ elk_version }}"
        source: pull

    - name: wait for kibana to start # Ожидание запуска kibana_server
      wait_for:
        host: "{{ groups['kibana_server'][0] }}"
        port: 5601

    - name: run filebeat # Запуск filebeat и настройка контейнера
      docker_container:
        name: "filebeat_{{ inventory_hostname }}"
        image: "elastic/filebeat:{{ elk_version }}"
        state: started
        user: root
        capabilities:
          - IPC_LOCK
        command: 
          - "--strict.perms=false"
        volumes:
          - "/media/filebeat.docker.yml:/usr/share/filebeat/filebeat.yml:ro"
          - "/var/lib/docker/containers:/var/lib/docker/containers:ro"
          - "/var/run/docker.sock:/var/run/docker.sock:ro"
          - "/var/log:/var/log:ro"

  handlers:
    - name: restart filebeat
      docker_container:
        name: "filebeat_{{ inventory_hostname }}"
        state: started
        restart: true